export const standforms = [
  {
    "username": "CC",
    "match": 46,
    "slot": "r1",
    "team": 6894,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Got stuck on algae for most of game"
  },
  {
    "username": "CC",
    "match": 45,
    "slot": "r1",
    "team": 8304,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 3,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Good processor scoring"
  },
  {
    "username": "CC",
    "match": 44,
    "slot": "r1",
    "team": 9724,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Played underwhelming defense"
  },
  {
    "username": "CC",
    "match": 43,
    "slot": "r1",
    "team": 8757,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow cycling"
  },
  {
    "username": "CC",
    "match": 42,
    "slot": "r1",
    "team": 4816,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got a coral stuck in their bot"
  },
  {
    "username": "CC",
    "match": 41,
    "slot": "r1",
    "team": 10302,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "ok cycling"
  },
  {
    "username": "CJ",
    "match": 39,
    "slot": "r1",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 1,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 38,
    "slot": "r1",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 0,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 37,
    "slot": "r1",
    "team": 10248,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 8,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 36,
    "slot": "r1",
    "team": 9297,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 10,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 35,
    "slot": "r1",
    "team": 10583,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 34,
    "slot": "r1",
    "team": 4816,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got algae stuck twice"
  },
  {
    "username": "CJ",
    "match": 33,
    "slot": "r1",
    "team": 6894,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 4,
    "teleopl2": 0,
    "teleopl3": 5,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Kept dropping coral"
  },
  {
    "username": "CJ",
    "match": 32,
    "slot": "r1",
    "team": 6729,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 2,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 31,
    "slot": "r1",
    "team": 8304,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 9,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "I think that was a processor score"
  },
  {
    "username": "JL",
    "match": 46,
    "slot": "r3",
    "team": 4534,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 45,
    "slot": "r3",
    "team": 3336,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 4,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 43,
    "slot": "r3",
    "team": 6729,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 41,
    "slot": "r3",
    "team": 3336,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": "Broke down due to running overalgae"
  },
  {
    "username": "AL",
    "match": 42,
    "slot": "r3",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Played defense in the second half"
  },
  {
    "username": "AL",
    "match": 44,
    "slot": "r3",
    "team": 10260,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Control was really bad. The robot was all over the plac"
  },
  {
    "username": "AL",
    "match": 40,
    "slot": "r3",
    "team": 9788,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense"
  },
  {
    "username": "AL",
    "match": 39,
    "slot": "r3",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 1,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "W defense, we love you chris"
  },
  {
    "username": "AL",
    "match": 38,
    "slot": "r3",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 7,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 36,
    "slot": "r3",
    "team": 10121,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 37,
    "slot": "r3",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 1,
    "noshow": 0,
    "notes": "Saved teammate from algae"
  },
  {
    "username": "AL",
    "match": 35,
    "slot": "r3",
    "team": 9296,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AL",
    "match": 34,
    "slot": "r3",
    "team": 8304,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 3,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Cockblocked"
  },
  {
    "username": "AL",
    "match": 33,
    "slot": "r3",
    "team": 8205,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "DC for 20s"
  },
  {
    "username": "AL",
    "match": 31,
    "slot": "r3",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 7,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Wrong side auto"
  },
  {
    "username": "AL",
    "match": 32,
    "slot": "r3",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 8,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Locked in"
  },
  {
    "username": "EM",
    "match": 46,
    "slot": "b1",
    "team": 9297,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 8,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 45,
    "slot": "b1",
    "team": 6512,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 44,
    "slot": "b1",
    "team": 3349,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 43,
    "slot": "b1",
    "team": 9198,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 6,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 42,
    "slot": "b1",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 41,
    "slot": "b1",
    "team": 10121,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 6,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Ha",
    "match": 40,
    "slot": "b1",
    "team": 435,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "All defense"
  },
  {
    "username": "Ha",
    "match": 39,
    "slot": "b1",
    "team": 9296,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 5,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got some algae"
  },
  {
    "username": "Ha",
    "match": 38,
    "slot": "b1",
    "team": 5518,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense"
  },
  {
    "username": "Ha",
    "match": 37,
    "slot": "b1",
    "team": 8205,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 3,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Good at getting L2s and L3s"
  },
  {
    "username": "Ha",
    "match": 35,
    "slot": "b1",
    "team": 9788,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Some coral L1"
  },
  {
    "username": "Ha",
    "match": 36,
    "slot": "b1",
    "team": 3336,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "None"
  },
  {
    "username": "Ha",
    "match": 34,
    "slot": "b1",
    "team": 9198,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Got like 3 algae"
  },
  {
    "username": "Ha",
    "match": 33,
    "slot": "b1",
    "team": 4534,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Ha",
    "match": 32,
    "slot": "b1",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 5,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Seems to get all levels"
  },
  {
    "username": "Ha",
    "match": 31,
    "slot": "b1",
    "team": 9297,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 10,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Just level 3s but did well"
  },
  {
    "username": "WD",
    "match": 46,
    "slot": "b3",
    "team": 4816,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Played defense"
  },
  {
    "username": "WD",
    "match": 45,
    "slot": "b3",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 7,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 44,
    "slot": "b3",
    "team": 10248,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 43,
    "slot": "b3",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 42,
    "slot": "b3",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Parked as soon as tele started"
  },
  {
    "username": "WD",
    "match": 41,
    "slot": "b3",
    "team": 10248,
    "startingzone": 0,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Sr",
    "match": 40,
    "slot": "b3",
    "team": 4534,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 10,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Rlly good"
  },
  {
    "username": "Sr",
    "match": 39,
    "slot": "b3",
    "team": 10583,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": "Stopped working"
  },
  {
    "username": "Sr",
    "match": 38,
    "slot": "b3",
    "team": 10260,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 1,
    "notes": ""
  },
  {
    "username": "Sr",
    "match": 37,
    "slot": "b3",
    "team": 5607,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 2,
    "teleopl3": 3,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Sr",
    "match": 36,
    "slot": "b3",
    "team": 9724,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Sr",
    "match": 34,
    "slot": "b3",
    "team": 8757,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 1,
    "notes": ""
  },
  {
    "username": "JL",
    "match": 33,
    "slot": "b3",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 1,
    "teleopl2": 6,
    "teleopl3": 2,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 32,
    "slot": "b3",
    "team": 5607,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 5,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 31,
    "slot": "b3",
    "team": 5518,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Didn't ro much"
  },
  {
    "username": "TI",
    "match": 46,
    "slot": "b2",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "TI",
    "match": 45,
    "slot": "b2",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "End effector got stuck for a bit, then unstuck"
  },
  {
    "username": "TI",
    "match": 44,
    "slot": "b2",
    "team": 10302,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 2,
    "teleopnet": 1,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "TI",
    "match": 43,
    "slot": "b2",
    "team": 7443,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Put 2 coral on l3 while algae was there"
  },
  {
    "username": "TI",
    "match": 42,
    "slot": "b2",
    "team": 10583,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 2,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Manual align"
  },
  {
    "username": "TI",
    "match": 41,
    "slot": "b2",
    "team": 9724,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow defense, ran into deep cage and got stuck"
  },
  {
    "username": "Kr",
    "match": 40,
    "slot": "b2",
    "team": 6512,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": "Barely moved"
  },
  {
    "username": "Kr",
    "match": 39,
    "slot": "b2",
    "team": 9297,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Kr",
    "match": 38,
    "slot": "b2",
    "team": 8304,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Kr",
    "match": 36,
    "slot": "b2",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 7,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Kr",
    "match": 37,
    "slot": "b2",
    "team": 9198,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Kr",
    "match": 35,
    "slot": "b2",
    "team": 10260,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Seems like something in drive base is iff"
  },
  {
    "username": "Kr",
    "match": 34,
    "slot": "b2",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense"
  },
  {
    "username": "Kr",
    "match": 33,
    "slot": "b2",
    "team": 10077,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 3,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Parked early"
  },
  {
    "username": "Kr",
    "match": 32,
    "slot": "b2",
    "team": 435,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow intake"
  },
  {
    "username": "Kr",
    "match": 31,
    "slot": "b2",
    "team": 10248,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense"
  },
  {
    "username": "NT",
    "match": 45,
    "slot": "r2",
    "team": 5607,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 46,
    "slot": "r2",
    "team": 10121,
    "startingzone": 0,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 4,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Didn't help Java when on alge"
  },
  {
    "username": "NT",
    "match": 43,
    "slot": "r2",
    "team": 9788,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 44,
    "slot": "r2",
    "team": 435,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Tsssssssssss"
  },
  {
    "username": "NT",
    "match": 42,
    "slot": "r2",
    "team": 9296,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 41,
    "slot": "r2",
    "team": 6894,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 6,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 40,
    "slot": "r2",
    "team": 8757,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 1,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 39,
    "slot": "r2",
    "team": 6729,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "2 algae opponent processor"
  },
  {
    "username": "LD",
    "match": 38,
    "slot": "r2",
    "team": 3349,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 37,
    "slot": "r2",
    "team": 7443,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 1,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Stood in front of opponent processor"
  },
  {
    "username": "LD",
    "match": 35,
    "slot": "r2",
    "team": 5518,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 2,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 1,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 36,
    "slot": "r2",
    "team": 6512,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 34,
    "slot": "r2",
    "team": 3349,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Missed like half their l4 attempts"
  },
  {
    "username": "LD",
    "match": 33,
    "slot": "r2",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LD",
    "match": 32,
    "slot": "r2",
    "team": 7443,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense"
  },
  {
    "username": "LD",
    "match": 31,
    "slot": "r2",
    "team": 9198,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Kidnapped 6 algae from other side for teammates"
  }
];