export const standforms = [
  {
    "username": "AM",
    "match": 71,
    "slot": "r3",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 3,
    "teleopl2": 2,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Can only score one in auto"
  },
  {
    "username": "AM",
    "match": 70,
    "slot": "r3",
    "team": 10583,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Very janky elevator"
  },
  {
    "username": "AM",
    "match": 69,
    "slot": "r3",
    "team": 3737,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 5,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AM",
    "match": 68,
    "slot": "r3",
    "team": 9008,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 8,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": "They can retract coral if it is misaligned"
  },
  {
    "username": "AM",
    "match": 67,
    "slot": "r3",
    "team": 587,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 5,
    "teleopl4": 4,
    "teleopprocessor": 2,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Very efficient, did not misalign"
  },
  {
    "username": "AM",
    "match": 66,
    "slot": "r3",
    "team": 5727,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AM",
    "match": 65,
    "slot": "r3",
    "team": 6502,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 3,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 1,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Unreliable algae net placement,   got stuck on net rim"
  },
  {
    "username": "AM",
    "match": 64,
    "slot": "r3",
    "team": 3229,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Misaligned every shot (almost)"
  },
  {
    "username": "AM",
    "match": 63,
    "slot": "r2",
    "team": 4829,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 3,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "AM",
    "match": 62,
    "slot": "r3",
    "team": 9496,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 4,
    "teleopl3": 5,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "So efficient"
  },
  {
    "username": "AM",
    "match": 61,
    "slot": "r3",
    "team": 9298,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Decent defense"
  },
  {
    "username": "AM",
    "match": 60,
    "slot": "r3",
    "team": 8429,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ".three L4 in auto, crashout in teleop"
  },
  {
    "username": "MJ",
    "match": 71,
    "slot": "r2",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 8,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Tgsxvbb"
  },
  {
    "username": "MJ",
    "match": 70,
    "slot": "r2",
    "team": 3506,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Ground pickup a few missed coral"
  },
  {
    "username": "MJ",
    "match": 69,
    "slot": "r2",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 4,
    "teleopl3": 2,
    "teleopl4": 8,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "1miss in auto 5 in teleop"
  },
  {
    "username": "MJ",
    "match": 68,
    "slot": "r2",
    "team": 8746,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Multiple missednattempts at getting coral in intake temporarily got coral stuck in intake"
  },
  {
    "username": "MJ",
    "match": 67,
    "slot": "r2",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 7,
    "teleopl3": 2,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Missed 2 algae attempts in barge by robot"
  },
  {
    "username": "MJ",
    "match": 66,
    "slot": "r2",
    "team": 2642,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Started off slow and leggy but got a bit better"
  },
  {
    "username": "MJ",
    "match": 65,
    "slot": "r2",
    "team": 5190,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 4,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Can remove algae unsure if intentional or not"
  },
  {
    "username": "LD",
    "match": 64,
    "slot": "r2",
    "team": 4561,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Missing most of their shots (rizzless)"
  },
  {
    "username": "LD",
    "match": 63,
    "slot": "r2",
    "team": 4829,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "2 penalties from groping 2 blue cages, was being useless in beginning of match?"
  },
  {
    "username": "Ld",
    "match": 62,
    "slot": "r2",
    "team": 7763,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 4,
    "teleopl2": 2,
    "teleopl3": 4,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Started shaking had seizure or smth but was ok?"
  },
  {
    "username": "LD",
    "match": 61,
    "slot": "r2",
    "team": 4795,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 1,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 6,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Tippy when elevator up/doing net"
  },
  {
    "username": "LD",
    "match": 60,
    "slot": "r2",
    "team": 5511,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 1,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "1 dealgae auto"
  },
  {
    "username": "WD",
    "match": 71,
    "slot": "b1",
    "team": 8429,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Sr",
    "match": 70,
    "slot": "b1",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 2,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Fast scoring and good overall"
  },
  {
    "username": "Sr",
    "match": 69,
    "slot": "b1",
    "team": 6502,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Autotweaked, couldn't score, defended a Lil and parked early"
  },
  {
    "username": "Sr",
    "match": 68,
    "slot": "b1",
    "team": 6729,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 4,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": "Stopped moving with 30 sec left"
  },
  {
    "username": "Sr",
    "match": 67,
    "slot": "b1",
    "team": 1533,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 0,
    "teleopl4": 7,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": "Pretty good , defense against 7443 got a bit heated"
  },
  {
    "username": "Sr",
    "match": 66,
    "slot": "b1",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 10,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Jerky driving fast scoring"
  },
  {
    "username": "Sr",
    "match": 65,
    "slot": "b1",
    "team": 8429,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Scoring was a little iffy during teleop . Auto ate"
  },
  {
    "username": "Sr",
    "match": 64,
    "slot": "b1",
    "team": 8727,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 3,
    "teleopl2": 1,
    "teleopl3": 2,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Teleop scoring was mid"
  },
  {
    "username": "Sr",
    "match": 63,
    "slot": "b1",
    "team": 8746,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ".good l4 scoring"
  },
  {
    "username": "Sr",
    "match": 62,
    "slot": "b1",
    "team": 10260,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Auto was wierd and just defended"
  },
  {
    "username": "Sr",
    "match": 61,
    "slot": "b1",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 6,
    "teleopl3": 5,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "So good smash I'm down bad"
  },
  {
    "username": "Sr",
    "match": 60,
    "slot": "b1",
    "team": 9297,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 9,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ".pretty fast in scoring"
  },
  {
    "username": "Yy",
    "match": 71,
    "slot": "r1",
    "team": 1533,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 3,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "H9ly shot their arm is s9 cooooolllll"
  },
  {
    "username": "Yy",
    "match": 70,
    "slot": "r1",
    "team": 5727,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 4,
    "teleopl3": 3,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Pretty consistent"
  },
  {
    "username": "Yy",
    "match": 69,
    "slot": "r1",
    "team": 4829,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 6,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 68,
    "slot": "r1",
    "team": 3229,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Spent beginning tweaking"
  },
  {
    "username": "Yy",
    "match": 67,
    "slot": "r1",
    "team": 7443,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Only played defense"
  },
  {
    "username": "Yy",
    "match": 66,
    "slot": "r1",
    "team": 6894,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 5,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 65,
    "slot": "r1",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 64,
    "slot": "r1",
    "team": 5511,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow elevator"
  },
  {
    "username": "Yy",
    "match": 63,
    "slot": "r1",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 5,
    "teleopl3": 4,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 1,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 62,
    "slot": "r1",
    "team": 2724,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 3,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 61,
    "slot": "r1",
    "team": 2640,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Yy",
    "match": 60,
    "slot": "r1",
    "team": 587,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 2,
    "teleopl2": 4,
    "teleopl3": 4,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "."
  },
  {
    "username": "JD",
    "match": 71,
    "slot": "b3",
    "team": 6500,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Good dealgaw, coral cycle time a llittl3 slow"
  },
  {
    "username": "LL",
    "match": 70,
    "slot": "b3",
    "team": 8738,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 4,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 69,
    "slot": "b3",
    "team": 4561,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 7,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": "."
  },
  {
    "username": "LL",
    "match": 68,
    "slot": "b3",
    "team": 4534,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 9,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Yaya wilmington!"
  },
  {
    "username": "LL",
    "match": 67,
    "slot": "b3",
    "team": 2724,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "."
  },
  {
    "username": "LL",
    "match": 66,
    "slot": "b3",
    "team": 3506,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 3,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 65,
    "slot": "b3",
    "team": 3459,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 2,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 64,
    "slot": "b3",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 2,
    "teleopl2": 3,
    "teleopl3": 4,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bs",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 63,
    "slot": "b3",
    "team": 6500,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 3,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 62,
    "slot": "b3",
    "team": 9198,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 3,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 61,
    "slot": "b3",
    "team": 4828,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "LL",
    "match": 60,
    "slot": "b3",
    "team": 3229,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 3,
    "teleopl2": 5,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "."
  },
  {
    "username": "JL",
    "match": 71,
    "slot": "b2",
    "team": 9198,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 10,
    "teleopnet": 9,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 70,
    "slot": "b1",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 1,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Algae removal a little clumsy but effective"
  },
  {
    "username": "EM",
    "match": 69,
    "slot": "b1",
    "team": 6502,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Outtake broke, played defense, kinda slow"
  },
  {
    "username": "EM",
    "match": 68,
    "slot": "b1",
    "team": 6729,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 4,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": "Ran into reef and estopped idk why"
  },
  {
    "username": "EM",
    "match": 67,
    "slot": "b1",
    "team": 1533,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 1,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 0,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Very fast climb"
  },
  {
    "username": "EM",
    "match": 66,
    "slot": "b1",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 8,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 65,
    "slot": "b1",
    "team": 8429,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Poor accuracy"
  },
  {
    "username": "EM",
    "match": 64,
    "slot": "b1",
    "team": 8727,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 3,
    "teleopl1": 3,
    "teleopl2": 3,
    "teleopl3": 3,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got Hitchhikers off algae"
  },
  {
    "username": "EM",
    "match": 63,
    "slot": "b1",
    "team": 8746,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Their wiring makes me nervous"
  },
  {
    "username": "EM",
    "match": 62,
    "slot": "b1",
    "team": 10260,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 1,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Played defense not amazingly but not terribly"
  },
  {
    "username": "EM",
    "match": 61,
    "slot": "b1",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 6,
    "teleopl3": 5,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 60,
    "slot": "b1",
    "team": 9297,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 8,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Auto a little off but cooked otherwise"
  }
];