export const standforms = [
  {
    "username": "NT",
    "match": 1,
    "slot": "r2",
    "team": 10260,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 6,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Not a bad kitbot"
  },
  {
    "username": "NT",
    "match": 2,
    "slot": "r2",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 2,
    "teleopl3": 0,
    "teleopl4": 8,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Best team no question"
  },
  {
    "username": "NT",
    "match": 3,
    "slot": "r2",
    "team": 6512,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 4,
    "slot": "r2",
    "team": 8757,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 5,
    "slot": "r2",
    "team": 9724,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 6,
    "slot": "r2",
    "team": 435,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 7,
    "slot": "r2",
    "team": 5518,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 8,
    "slot": "r2",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 6,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "NT",
    "match": 9,
    "slot": "r2",
    "team": 900,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 3,
    "teleopl3": 0,
    "teleopl4": 12,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "First Pick team lol"
  },
  {
    "username": "NT",
    "match": 10,
    "slot": "r2",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JL",
    "match": 11,
    "slot": "r2",
    "team": 6512,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 1,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JL",
    "match": 12,
    "slot": "r2",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 5,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Missed auto but did really well"
  },
  {
    "username": "WD",
    "match": 1,
    "slot": "b3",
    "team": 9297,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 6,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "can only do l3 and below, slow elevator"
  },
  {
    "username": "WD",
    "match": 2,
    "slot": "b3",
    "team": 4816,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 3,
    "slot": "b3",
    "team": 10121,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Only able to do l1, unreliable intake"
  },
  {
    "username": "WD",
    "match": 4,
    "slot": "b3",
    "team": 7443,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Nonfunctional auto, played defense for a bit"
  },
  {
    "username": "WD",
    "match": 5,
    "slot": "b3",
    "team": 3822,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 4,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 6,
    "slot": "b3",
    "team": 9297,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 5,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 7,
    "slot": "b3",
    "team": 10260,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 8,
    "slot": "b3",
    "team": 6512,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 1,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "WD",
    "match": 9,
    "slot": "b3",
    "team": 7443,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 1,
    "noshow": 0,
    "notes": "Average jagwires"
  },
  {
    "username": "WD",
    "match": 10,
    "slot": "b3",
    "team": 4534,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 8,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "SR",
    "match": 11,
    "slot": "b3",
    "team": 3349,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Stopped working with 1 min left in the match"
  },
  {
    "username": "SR",
    "match": 12,
    "slot": "b3",
    "team": 8757,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Missed auto and then got stuck over a ball"
  },
  {
    "username": "JD",
    "match": 1,
    "slot": "r3",
    "team": 2059,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "They were slow with placing the corals"
  },
  {
    "username": "JD",
    "match": 2,
    "slot": "r3",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 5,
    "teleopl3": 2,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "They were a bit shaky and auto wasn't good"
  },
  {
    "username": "JD",
    "match": 3,
    "slot": "r3",
    "team": 8205,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 4,
    "slot": "r3",
    "team": 3349,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 5,
    "slot": "r3",
    "team": 10302,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 1,
    "teleopprocessor": 3,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 6,
    "slot": "r3",
    "team": 4816,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 8,
    "slot": "r3",
    "team": 9788,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 5,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 9,
    "slot": "r3",
    "team": 9198,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 3,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "JD",
    "match": 10,
    "slot": "r3",
    "team": 10248,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 4,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Played defense in the beginning"
  },
  {
    "username": "AL",
    "match": 11,
    "slot": "r3",
    "team": 5518,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Spent a minute dilly dallying, rest playing okay defens"
  },
  {
    "username": "AL",
    "match": 12,
    "slot": "r3",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 3,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Bad defense :("
  },
  {
    "username": "CJ",
    "match": 1,
    "slot": "b1",
    "team": 10077,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 6,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 2,
    "slot": "b1",
    "team": 6729,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 3,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 3,
    "slot": "b1",
    "team": 435,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 4,
    "slot": "b1",
    "team": 4534,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 2,
    "teleopl1": 1,
    "teleopl2": 5,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 5,
    "slot": "b1",
    "team": 9042,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 7,
    "slot": "b1",
    "team": 8757,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 8,
    "slot": "b1",
    "team": 3349,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 9,
    "slot": "b1",
    "team": 10302,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 2,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "EM",
    "match": 10,
    "slot": "b1",
    "team": 8304,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "ba",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "Ha",
    "match": 11,
    "slot": "b1",
    "team": 6894,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 5,
    "teleopl3": 5,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Very good at getting corals at low-levels"
  },
  {
    "username": "Ha",
    "match": 12,
    "slot": "b1",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "The robot malfunctioned"
  },
  {
    "username": "TI",
    "match": 1,
    "slot": "b2",
    "team": 9788,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Defense bot, missed l1 auto, ok defense"
  },
  {
    "username": "TI",
    "match": 2,
    "slot": "b2",
    "team": 10248,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Took almost the entire match to intake one piece"
  },
  {
    "username": "TI",
    "match": 3,
    "slot": "b2",
    "team": 3336,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 4,
    "teleopnet": 4,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Knocked over field pieces for auto"
  },
  {
    "username": "TI",
    "match": 4,
    "slot": "b2",
    "team": 6894,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 4,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Manual score, missed 2 l3, 4 l1"
  },
  {
    "username": "TI",
    "match": 5,
    "slot": "b2",
    "team": 8304,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 1,
    "teleopnet": 1,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got coral stuck during auto"
  },
  {
    "username": "TI",
    "match": 6,
    "slot": "b2",
    "team": 6729,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 2,
    "teleopprocessor": 0,
    "teleopnet": 2,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "Slow at scoring, 3 l4 miss"
  },
  {
    "username": "TI",
    "match": 7,
    "slot": "b2",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 6,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "3 l4 misses"
  },
  {
    "username": "TI",
    "match": 8,
    "slot": "b2",
    "team": 9724,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "2 l1 miss, took a while to intake"
  },
  {
    "username": "TI",
    "match": 9,
    "slot": "b2",
    "team": 9032,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 3,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Got piece stuck during auto, unstuck, and stuck again"
  },
  {
    "username": "TI",
    "match": 10,
    "slot": "b2",
    "team": 9296,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 4,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Delgae, l1 cycle"
  },
  {
    "username": "TI",
    "match": 11,
    "slot": "b2",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 3,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow l4 cycle, 2 l4 miss, delgae"
  },
  {
    "username": "TI",
    "match": 11,
    "slot": "b2",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 3,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 1,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Slow l4 cycle, 2 l4 miss, delgae"
  },
  {
    "username": "KR",
    "match": 12,
    "slot": "b2",
    "team": 8205,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 2,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Had coral stuck but figured It put"
  },
  {
    "username": "CC",
    "match": 1,
    "slot": "r1",
    "team": 5607,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 1,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Would barely move and were attempting to dealgaed"
  },
  {
    "username": "CC",
    "match": 2,
    "slot": "r1",
    "team": 9296,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "We're having trouble with L1"
  },
  {
    "username": "CC",
    "match": 3,
    "slot": "r1",
    "team": 2640,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 5,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Cleared algae to score L3"
  },
  {
    "username": "CC",
    "match": 4,
    "slot": "r1",
    "team": 5518,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": "When elevator is out, can be a bit tippy,"
  },
  {
    "username": "CC",
    "match": 5,
    "slot": "r1",
    "team": 10583,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 1,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Decent scoring, then switched to play a bit of defense"
  },
  {
    "username": "CC",
    "match": 6,
    "slot": "r1",
    "team": 10077,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 3,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CC",
    "match": 7,
    "slot": "r1",
    "team": 8205,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Played decent defense"
  },
  {
    "username": "CC",
    "match": 8,
    "slot": "r1",
    "team": 10583,
    "startingzone": 0,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 3,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CC",
    "match": 9,
    "slot": "r1",
    "team": 10121,
    "startingzone": 1,
    "autol1": 1,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 4,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": "Decent cycling L1"
  },
  {
    "username": "CC",
    "match": 10,
    "slot": "r1",
    "team": 3336,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 0,
    "teleopl2": 0,
    "teleopl3": 0,
    "teleopl4": 0,
    "teleopprocessor": 2,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bd",
    "died": 0,
    "noshow": 0,
    "notes": "Decent processor scoring"
  },
  {
    "username": "CJ",
    "match": 11,
    "slot": "r1",
    "team": 5607,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 1,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 3,
    "teleopl2": 0,
    "teleopl3": 2,
    "teleopl4": 0,
    "teleopprocessor": 0,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "x",
    "died": 0,
    "noshow": 0,
    "notes": ""
  },
  {
    "username": "CJ",
    "match": 12,
    "slot": "r1",
    "team": 10302,
    "startingzone": 1,
    "autol1": 0,
    "autol2": 0,
    "autol3": 0,
    "autol4": 0,
    "teleopl1": 1,
    "teleopl2": 0,
    "teleopl3": 1,
    "teleopl4": 0,
    "teleopprocessor": 2,
    "teleopnet": 0,
    "fouls": 0,
    "techfouls": 0,
    "endgame": "bp",
    "died": 0,
    "noshow": 0,
    "notes": ""
  }
];